services:
  ssh-target:
    image: linuxserver/openssh-server:latest
    container_name: ssh-target
    environment:
      - USER_NAME=pi
      - USER_PASSWORD=disabled
      - PUBLIC_KEY_FILE=/config/keys/authorized_keys
      - SUDO_ACCESS=true
    volumes:
      - ./scripts/ssh-test/authorized_keys:/config/keys/authorized_keys:ro
      - ./scripts/ssh-test/remote:/remote
    ports:
      - "2222:2222"

